env: standard
runtime: ruby27

automatic_scaling:
  min_idle_instances: 1
  min_instances: 1
  max_instances: 1

env_variables:
  RAILS_ENV: production
  SECRET_KEY_BASE: 0cb63b46511df1dc609fb5103f9475a218072b05bc300a0fe0b9f0d445ccb42a80c9a5af1cf974d9044441dae7fdf6bd277e33ee43f952b73512411e75ffb9db
  INSTANCE_UNIX_SOCKET: /cloudsql/ecommerce-api-390102:us-central1:ecommerce-api-db
  DB_USER: pedro-admin
  DB_PASS: admin2207
  DB_NAME: ecommerce-db


beta_settings:
  cloud_sql_instances: ecommerce-api-390102:us-central1:ecommerce-api-db