version: '3'
services:
  api:
    build: .
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=ecommerce
      - DATABASE_PASSWORD=ecommerce
  db:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=ecommerce
      - DATABASE_URL=postgresql://ecommerce:ecommerce@db:5433/ecommerce
