default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce
  host: db
  username: ecommerce
  password: ecommerce

test:
  <<: *default
  database: ecommerce

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  connect_timeout: 5
  variables:
    statement_timeout: 15s
    lock_timeout: 10s
